// 14-TypeScript/Grey Multi-Tenant/packages/grey-nuxt/src/provider/GreyProvider.vue
<script lang="ts">
/**
 * Grey Nuxt - GreyProvider Component
 *
 * Root provider component for Grey Multi-Tenant.
 * Provides Grey context to all child components via Vue's provide/inject.
 *
 * Uses the PROVIDER TEMPLATE (Vue variant).
 * No UI logic, only wiring.
 */

import { defineComponent, provide } from 'vue';
import { useAuth } from '../composables/useAuth.js';
import { useUser } from '../composables/useUser.js';
import { useProjects } from '../composables/useProjects.js';
import { GreyKey, type GreyContextValue } from './types.js';

export default defineComponent({
  name: 'GreyProvider',

  setup(_, { slots }) {
    // Initialize composables
    const auth = useAuth();
    const user = useUser();
    const projects = useProjects();

    // Provide context to child components
    const contextValue: GreyContextValue = {
      auth,
      user,
      projects,
    };

    provide(GreyKey, contextValue);

    // Render slot content
    return () => {
      return slots.default ? slots.default() : null;
    };
  },
});
</script>

// 14-TypeScript/Grey Multi-Tenant/packages/grey-sveltekit/src/provider/GreyProvider.svelte
<script lang="ts">
/**
 * Grey SvelteKit - GreyProvider Component
 *
 * Root provider component for Grey Multi-Tenant.
 * Provides Grey stores to all child components via Svelte's setContext.
 *
 * Uses the PROVIDER TEMPLATE (Svelte variant).
 * No UI logic, only wiring. SSR-safe.
 */

import { setContext } from 'svelte';
import { createAuthStore } from '../stores/auth.js';
import { createUserStore } from '../stores/user.js';
import { createProjectsStore } from '../stores/projects.js';
import { GREY_CONTEXT_KEY, type GreyContextValue } from './types.js';

/**
 * Props
 */
export let baseUrl: string = '';

// Initialize stores
const auth = createAuthStore(baseUrl);
const user = createUserStore();
const projects = createProjectsStore();

// Provide context to child components
const contextValue: GreyContextValue = {
  auth,
  user,
  projects,
};

setContext(GREY_CONTEXT_KEY, contextValue);
</script>

<slot />
