// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/hooks/useUser.ts
/**
 * Grey Solid - useUser Hook
 *
 * Solid hook for user state and actions.
 * Wraps UserController from @grey/adapters.
 * Exposes: data, loading, error, fetchUser.
 */

import { createSignal, onMount, onCleanup, type Accessor } from 'solid-js';
import { UserController, type UserState } from '@grey/adapters';
import type { GreyClient, User } from '@grey/core-client';

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * useUser hook return type
 */
export interface UseUserReturn {
  /** User data */
  data: Accessor<User | null>;
  /** Loading state */
  loading: Accessor<boolean>;
  /** Error state */
  error: Accessor<GreyError | null>;
  /** Fetch current user */
  fetchUser: () => Promise<User | null>;
}

/**
 * Normalize error into standard shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return { message: err.message, raw: err };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return { message: 'An unknown error occurred', raw: err };
}

/**
 * useUser hook
 *
 * @param client - Grey API client
 * @returns User hook with data, loading, error, and actions
 */
export function useUser(client: GreyClient): UseUserReturn {
  const controller = new UserController(client);

  // Create signals
  const [data, setData] = createSignal<User | null>(null);
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<GreyError | null>(null);

  // Subscribe to controller state changes
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    unsubscribe = controller.subscribe((state: UserState) => {
      setData(state.user);
      setLoading(state.isLoading);
      if (state.error) {
        setError({ message: state.error });
      }
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  /**
   * Fetch current user
   */
  async function fetchUser(): Promise<User | null> {
    setLoading(true);
    setError(null);
    try {
      const user = await controller.fetchCurrentUser();
      setLoading(false);
      return user;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return null;
    }
  }

  return {
    data,
    loading,
    error,
    fetchUser,
  };
}

export type { UserState };

// 14-TypeScript/Grey Multi-Tenant/packages/grey-qwik/src/composables/useUser.ts
/**
 * Grey Qwik - useUser Composable
 *
 * Provides current user state using Qwik's reactive primitives.
 * Must be used within a GreyProvider.
 *
 * @example
 * ```tsx
 * import { component$ } from '@builder.io/qwik';
 * import { useUser } from '@grey/qwik';
 *
 * export default component$(() => {
 *   const { user, isLoading, refresh$ } = useUser();
 *
 *   return (
 *     <div>
 *       {isLoading.value ? (
 *         <p>Loading...</p>
 *       ) : user.value ? (
 *         <div>
 *           <h1>{user.value.name}</h1>
 *           <p>{user.value.email}</p>
 *           <button onClick$={refresh$}>Refresh</button>
 *         </div>
 *       ) : null}
 *     </div>
 *   );
 * });
 * ```
 */

import { useSignal, useVisibleTask$, $ } from '@builder.io/qwik';
import type { UserState as CoreUserState } from '@grey/adapters';
import type { User } from '@grey/core-client';
import { useGreyContext } from '../context/index.js';
import type { UserComposable } from '../types/index.js';

/**
 * useUser Composable
 *
 * Wraps the UserController from @grey/adapters and exposes
 * Qwik signals for reactive state access.
 *
 * @returns User composable with state signals and actions
 *
 * @example
 * ```tsx
 * export default component$(() => {
 *   const { user, isLoading } = useUser();
 *
 *   return (
 *     <div>
 *       {isLoading.value ? (
 *         <Spinner />
 *       ) : user.value ? (
 *         <Avatar src={user.value.avatar_url} alt={user.value.name} />
 *       ) : null}
 *     </div>
 *   );
 * });
 * ```
 */
export function useUser(): UserComposable {
  const { userController } = useGreyContext();

  // Create signals with initial state from controller
  const state = useSignal<CoreUserState>(userController.getState());
  const user = useSignal(state.value.user);
  const isLoading = useSignal(state.value.isLoading);
  const error = useSignal<string | null>(state.value.error);

  // Subscribe to controller state changes (client-side only)
  useVisibleTask$(({ cleanup }: { cleanup: (fn: () => void) => void }) => {
    const unsubscribe = userController.subscribe((newState: CoreUserState) => {
      state.value = newState;
      user.value = newState.user;
      isLoading.value = newState.isLoading;
      error.value = newState.error;
    });

    cleanup(() => {
      unsubscribe();
    });
  });

  /**
   * Refresh user data from API
   */
  const refresh$ = $(async (): Promise<User | null> => {
    return userController.fetchCurrentUser();
  });

  /**
   * Clear user state
   */
  const clear$ = $(() => {
    userController.clearUser();
  });

  /**
   * Clear current error
   */
  const clearError$ = $(() => {
    userController.clearError();
  });

  return {
    state,
    user,
    isLoading,
    error,
    refresh$,
    clear$,
    clearError$,
  };
}
