// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/provider/GreyProvider.tsx
/**
 * Grey Solid - GreyProvider
 *
 * Root provider component that wraps the application and provides
 * Grey state and actions to all child components via Solid context.
 * No UI logic, only wiring.
 */

import { createContext, useContext, type JSX, type Accessor } from 'solid-js';
import { useAuth, type UseAuthReturn, type AuthConfig } from '../hooks/useAuth.js';
import { useUser, type UseUserReturn } from '../hooks/useUser.js';
import { useProjects, type UseProjectsReturn } from '../hooks/useProjects.js';
import type { GreyClient } from '@grey/core-client';

/**
 * Context types
 */
export interface GreyAuthContextValue extends UseAuthReturn {}
export interface GreyUserContextValue extends UseUserReturn {}
export interface GreyProjectsContextValue extends UseProjectsReturn {}

/**
 * Create contexts
 */
export const GreyAuthContext = createContext<GreyAuthContextValue>();
export const GreyUserContext = createContext<GreyUserContextValue>();
export const GreyProjectsContext = createContext<GreyProjectsContextValue>();
export const GreyClientContext = createContext<GreyClient>();

/**
 * GreyProvider props
 */
export interface GreyProviderProps {
  /** Base URL for the Grey API (required) */
  apiBaseUrl: string;
  /** Children */
  children: JSX.Element;
}

/**
 * GreyProvider component
 *
 * Root provider that initializes all Grey hooks and provides them
 * via Solid's context system to all child components.
 */
export function GreyProvider(props: GreyProviderProps): JSX.Element {
  // Initialize auth hook
  const auth = useAuth({ apiBaseUrl: props.apiBaseUrl });
  const client = auth.getClient();

  // Initialize user and projects hooks
  const user = useUser(client);
  const projects = useProjects(client);

  return (
    <GreyAuthContext.Provider value={auth}>
      <GreyUserContext.Provider value={user}>
        <GreyProjectsContext.Provider value={projects}>
          <GreyClientContext.Provider value={client}>
            {props.children}
          </GreyClientContext.Provider>
        </GreyProjectsContext.Provider>
      </GreyUserContext.Provider>
    </GreyAuthContext.Provider>
  );
}

/**
 * useGreyAuth - Get auth context
 */
export function useGreyAuth(): GreyAuthContextValue {
  const context = useContext(GreyAuthContext);
  if (!context) {
    throw new Error('[Grey Solid] useGreyAuth must be used within a GreyProvider');
  }
  return context;
}

/**
 * useGreyUser - Get user context
 */
export function useGreyUser(): GreyUserContextValue {
  const context = useContext(GreyUserContext);
  if (!context) {
    throw new Error('[Grey Solid] useGreyUser must be used within a GreyProvider');
  }
  return context;
}

/**
 * useGreyProjects - Get projects context
 */
export function useGreyProjects(): GreyProjectsContextValue {
  const context = useContext(GreyProjectsContext);
  if (!context) {
    throw new Error('[Grey Solid] useGreyProjects must be used within a GreyProvider');
  }
  return context;
}

/**
 * useGreyClient - Get Grey API client
 */
export function useGreyClient(): GreyClient {
  const context = useContext(GreyClientContext);
  if (!context) {
    throw new Error('[Grey Solid] useGreyClient must be used within a GreyProvider');
  }
  return context;
}

export default GreyProvider;

// 14-TypeScript/Grey Multi-Tenant/packages/grey-next/src/provider/GreyProvider.tsx
'use client';

/**
 * GreyProvider - Next.js Client Component for context provision
 *
 * Provides Grey contexts for auth, user, projects, query, and mutation.
 * Renders children directly.
 * No UI logic.
 */

import React, { createContext, useContext, useMemo, type ReactNode } from 'react';
import { useAuth, type UseAuthReturn } from '../hooks/useAuth.js';
import { useUser, type UseUserReturn } from '../hooks/useUser.js';
import { useProjects, type UseProjectsReturn } from '../hooks/useProjects.js';

// =============================================================================
// Context Types
// =============================================================================

export interface GreyContextValue {
  auth: UseAuthReturn;
  user: UseUserReturn;
  projects: UseProjectsReturn;
}

// =============================================================================
// Context
// =============================================================================

const GreyContext = createContext<GreyContextValue | null>(null);

// =============================================================================
// Provider
// =============================================================================

export interface GreyProviderProps {
  children: ReactNode;
}

export function GreyProvider({ children }: GreyProviderProps): React.JSX.Element {
  const auth = useAuth();
  const user = useUser();
  const projects = useProjects();

  const value = useMemo<GreyContextValue>(
    () => ({
      auth,
      user,
      projects,
    }),
    [auth, user, projects]
  );

  return (
    <GreyContext.Provider value={value}>
      {children}
    </GreyContext.Provider>
  );
}

// =============================================================================
// Context Hooks
// =============================================================================

export function useGreyContext(): GreyContextValue {
  const context = useContext(GreyContext);
  if (!context) {
    throw new Error('useGreyContext must be used within a GreyProvider');
  }
  return context;
}

export function useGreyAuth(): UseAuthReturn {
  return useGreyContext().auth;
}

export function useGreyUser(): UseUserReturn {
  return useGreyContext().user;
}

export function useGreyProjects(): UseProjectsReturn {
  return useGreyContext().projects;
}
