// 14-TypeScript/Grey Multi-Tenant/packages/grey-react-native/src/hooks/useAuth.ts
/**
 * Grey React Native - useAuth Hook
 *
 * Provides authentication state and actions for React Native components.
 * Wraps the AuthController from @grey/adapters.
 * Mobile-safe: no browser/DOM APIs.
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import {
  AuthController,
  MemoryTokenStorage,
  type AuthState as CoreAuthState,
  type AuthConfig,
} from '@grey/adapters';

// ============================================================
// Types
// ============================================================

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * Auth hook return type
 */
export interface UseAuthReturn {
  data: CoreAuthState;
  loading: boolean;
  error: GreyError | null;
  login: (email: string, password: string) => Promise<boolean>;
  logout: () => Promise<void>;
  refresh: () => Promise<boolean>;
}

// ============================================================
// Error Normalization
// ============================================================

/**
 * Normalize any error into the standard error shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return {
      message: err.message,
      raw: err,
    };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return {
    message: 'An unknown error occurred',
    raw: err,
  };
}

// ============================================================
// Hook Implementation
// ============================================================

/**
 * useAuth Hook
 *
 * Provides authentication state and actions.
 * Must be used within a GreyProvider or with a config.
 * Uses MemoryTokenStorage by default (mobile-safe).
 *
 * @param config - Optional auth configuration for standalone usage
 */
export function useAuth(config?: AuthConfig): UseAuthReturn {
  const controllerRef = useRef<AuthController | null>(null);
  const [data, setData] = useState<CoreAuthState>({
    user: null,
    isAuthenticated: false,
    isLoading: false,
    error: null,
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<GreyError | null>(null);

  // Track if component is mounted
  const mountedRef = useRef(true);
  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // Initialize controller
  useEffect(() => {
    if (!config) return;

    // Use MemoryTokenStorage for mobile-safe token storage
    const authConfig: AuthConfig = {
      ...config,
      tokenStorage: config.tokenStorage ?? new MemoryTokenStorage(),
    };

    const controller = new AuthController(authConfig);
    controllerRef.current = controller;

    const unsubscribe = controller.subscribe((state: CoreAuthState) => {
      if (mountedRef.current) {
        setData(state);
        setLoading(state.isLoading);
        if (state.error) {
          setError({ message: state.error });
        }
      }
    });

    // Restore session on mount
    controller.restoreSession().catch(() => {
      // Session restore failed, user not authenticated
    });

    return () => {
      unsubscribe();
    };
  }, [config?.apiBaseUrl]);

  /**
   * Login with email and password
   */
  const login = useCallback(async (email: string, password: string): Promise<boolean> => {
    const controller = controllerRef.current;
    if (!controller) {
      setError({ message: 'Auth controller not initialized' });
      return false;
    }

    setLoading(true);
    setError(null);

    try {
      const result = await controller.login(email, password);
      if (mountedRef.current) {
        setLoading(false);
      }
      return result;
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
      return false;
    }
  }, []);

  /**
   * Logout and clear session
   */
  const logout = useCallback(async (): Promise<void> => {
    const controller = controllerRef.current;
    if (!controller) {
      return;
    }

    setLoading(true);
    setError(null);

    try {
      controller.logout();
      if (mountedRef.current) {
        setLoading(false);
      }
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
    }
  }, []);

  /**
   * Refresh the session
   */
  const refresh = useCallback(async (): Promise<boolean> => {
    const controller = controllerRef.current;
    if (!controller) {
      setError({ message: 'Auth controller not initialized' });
      return false;
    }

    setLoading(true);
    setError(null);

    try {
      const result = await controller.restoreSession();
      if (mountedRef.current) {
        setLoading(false);
      }
      return result;
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
      return false;
    }
  }, []);

  return {
    data,
    loading,
    error,
    login,
    logout,
    refresh,
  };
}

// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/hooks/useAuth.ts
/**
 * Grey Solid - useAuth Hook
 *
 * Solid hook for authentication state and actions.
 * Wraps AuthController from @grey/adapters.
 * Exposes: data, loading, error, login, logout, refresh.
 */

import { createSignal, onMount, onCleanup, type Accessor } from 'solid-js';
import {
  AuthController,
  BrowserTokenStorage,
  MemoryTokenStorage,
  type AuthState,
  type AuthConfig,
} from '@grey/adapters';
import type { GreyClient } from '@grey/core-client';

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * useAuth hook return type
 */
export interface UseAuthReturn {
  /** Auth state data (user, isAuthenticated, etc.) */
  data: Accessor<AuthState>;
  /** Loading state */
  loading: Accessor<boolean>;
  /** Error state */
  error: Accessor<GreyError | null>;
  /** Login with email and password */
  login: (email: string, password: string) => Promise<boolean>;
  /** Logout and clear session */
  logout: () => Promise<void>;
  /** Refresh/restore session */
  refresh: () => Promise<boolean>;
  /** Get the API client */
  getClient: () => GreyClient;
}

/**
 * SSR-safe browser check
 */
function isBrowser(): boolean {
  return typeof window !== 'undefined' && typeof document !== 'undefined';
}

/**
 * Normalize error into standard shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return { message: err.message, raw: err };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return { message: 'An unknown error occurred', raw: err };
}

/**
 * useAuth hook
 *
 * @param config - Auth configuration (apiBaseUrl required)
 * @returns Auth hook with data, loading, error, and actions
 */
export function useAuth(config: AuthConfig): UseAuthReturn {
  // Use browser storage in browser, memory storage during SSR
  const storage = isBrowser() ? new BrowserTokenStorage() : new MemoryTokenStorage();

  const controller = new AuthController({
    ...config,
    storage: config.storage ?? storage,
  });

  // Create signals
  const [data, setData] = createSignal<AuthState>(controller.getState());
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<GreyError | null>(null);

  // Subscribe to controller state changes
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    unsubscribe = controller.subscribe((state: AuthState) => {
      setData(state);
      setLoading(state.isLoading);
      if (state.error) {
        setError({ message: state.error });
      }
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  /**
   * Login with email and password
   */
  async function login(email: string, password: string): Promise<boolean> {
    setLoading(true);
    setError(null);
    try {
      const result = await controller.login(email, password);
      setLoading(false);
      return result;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return false;
    }
  }

  /**
   * Logout and clear session
   */
  async function logout(): Promise<void> {
    setLoading(true);
    setError(null);
    try {
      controller.logout();
      setLoading(false);
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
    }
  }

  /**
   * Refresh/restore session
   */
  async function refresh(): Promise<boolean> {
    if (!isBrowser()) {
      return false;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await controller.restoreSession();
      setLoading(false);
      return result;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return false;
    }
  }

  /**
   * Get the API client
   */
  function getClient(): GreyClient {
    return controller.getClient();
  }

  return {
    data,
    loading,
    error,
    login,
    logout,
    refresh,
    getClient,
  };
}

export type { AuthState, AuthConfig };
