// 14-TypeScript/Grey Multi-Tenant/packages/grey-qwik/src/composables/useAuth.ts
/**
 * Grey Qwik - useAuth Composable
 *
 * Provides authentication state and actions using Qwik's reactive primitives.
 * Must be used within a GreyProvider.
 *
 * @example
 * ```tsx
 * import { component$ } from '@builder.io/qwik';
 * import { useAuth } from '@grey/qwik';
 *
 * export default component$(() => {
 *   const auth = useAuth();
 *
 *   return (
 *     <div>
 *       {auth.isAuthenticated.value ? (
 *         <button onClick$={auth.logout$}>Logout</button>
 *       ) : (
 *         <button onClick$={() => auth.login$('user@example.com', 'password')}>
 *           Login
 *         </button>
 *       )}
 *     </div>
 *   );
 * });
 * ```
 */

import { useSignal, useTask$, useVisibleTask$, $ } from '@builder.io/qwik';
import type { AuthState as CoreAuthState } from '@grey/adapters';
import { useGreyContext, isBrowser } from '../context/index.js';
import type { AuthComposable } from '../types/index.js';

/**
 * useAuth Composable
 *
 * Wraps the AuthController from @grey/adapters and exposes
 * Qwik signals for reactive state access.
 *
 * @returns Auth composable with state signals and actions
 *
 * @example
 * ```tsx
 * export default component$(() => {
 *   const auth = useAuth();
 *
 *   // Auto-restore session on mount using useVisibleTask$
 *   useVisibleTask$(async () => {
 *     await auth.restoreSession$();
 *   });
 *
 *   return (
 *     <div>
 *       {auth.isLoading.value && <p>Loading...</p>}
 *       {auth.error.value && <p class="error">{auth.error.value}</p>}
 *       {auth.isAuthenticated.value && (
 *         <p>Welcome, {auth.user.value?.email}</p>
 *       )}
 *     </div>
 *   );
 * });
 * ```
 */
export function useAuth(): AuthComposable {
  const { authController } = useGreyContext();

  // Create signals with initial state from controller
  const state = useSignal<CoreAuthState>(authController.getState());
  const isAuthenticated = useSignal(state.value.isAuthenticated);
  const isLoading = useSignal(state.value.isLoading);
  const error = useSignal<string | null>(state.value.error);
  const user = useSignal(state.value.user);

  // Subscribe to controller state changes (client-side only)
  // useVisibleTask$ ensures this only runs in the browser
  useVisibleTask$(({ cleanup }: { cleanup: (fn: () => void) => void }) => {
    const unsubscribe = authController.subscribe((newState: CoreAuthState) => {
      state.value = newState;
      isAuthenticated.value = newState.isAuthenticated;
      isLoading.value = newState.isLoading;
      error.value = newState.error;
      user.value = newState.user;
    });

    cleanup(() => {
      unsubscribe();
    });
  });

  /**
   * Login with email and password
   */
  const login$ = $(async (email: string, password: string): Promise<boolean> => {
    return authController.login(email, password);
  });

  /**
   * Logout and clear session
   */
  const logout$ = $(() => {
    authController.logout();
  });

  /**
   * Restore session from storage
   */
  const restoreSession$ = $(async (): Promise<boolean> => {
    if (!isBrowser()) {
      return false;
    }
    return authController.restoreSession();
  });

  /**
   * Clear current error
   */
  const clearError$ = $(() => {
    authController.clearError();
  });

  return {
    state,
    isAuthenticated,
    isLoading,
    error,
    user,
    login$,
    logout$,
    restoreSession$,
    clearError$,
  };
}

// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/hooks/useAuth.ts
/**
 * Grey Solid - useAuth Hook
 *
 * Solid hook for authentication state and actions.
 * Wraps AuthController from @grey/adapters.
 * Exposes: data, loading, error, login, logout, refresh.
 */

import { createSignal, onMount, onCleanup, type Accessor } from 'solid-js';
import {
  AuthController,
  BrowserTokenStorage,
  MemoryTokenStorage,
  type AuthState,
  type AuthConfig,
} from '@grey/adapters';
import type { GreyClient } from '@grey/core-client';

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * useAuth hook return type
 */
export interface UseAuthReturn {
  /** Auth state data (user, isAuthenticated, etc.) */
  data: Accessor<AuthState>;
  /** Loading state */
  loading: Accessor<boolean>;
  /** Error state */
  error: Accessor<GreyError | null>;
  /** Login with email and password */
  login: (email: string, password: string) => Promise<boolean>;
  /** Logout and clear session */
  logout: () => Promise<void>;
  /** Refresh/restore session */
  refresh: () => Promise<boolean>;
  /** Get the API client */
  getClient: () => GreyClient;
}

/**
 * SSR-safe browser check
 */
function isBrowser(): boolean {
  return typeof window !== 'undefined' && typeof document !== 'undefined';
}

/**
 * Normalize error into standard shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return { message: err.message, raw: err };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return { message: 'An unknown error occurred', raw: err };
}

/**
 * useAuth hook
 *
 * @param config - Auth configuration (apiBaseUrl required)
 * @returns Auth hook with data, loading, error, and actions
 */
export function useAuth(config: AuthConfig): UseAuthReturn {
  // Use browser storage in browser, memory storage during SSR
  const storage = isBrowser() ? new BrowserTokenStorage() : new MemoryTokenStorage();

  const controller = new AuthController({
    ...config,
    storage: config.storage ?? storage,
  });

  // Create signals
  const [data, setData] = createSignal<AuthState>(controller.getState());
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<GreyError | null>(null);

  // Subscribe to controller state changes
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    unsubscribe = controller.subscribe((state: AuthState) => {
      setData(state);
      setLoading(state.isLoading);
      if (state.error) {
        setError({ message: state.error });
      }
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  /**
   * Login with email and password
   */
  async function login(email: string, password: string): Promise<boolean> {
    setLoading(true);
    setError(null);
    try {
      const result = await controller.login(email, password);
      setLoading(false);
      return result;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return false;
    }
  }

  /**
   * Logout and clear session
   */
  async function logout(): Promise<void> {
    setLoading(true);
    setError(null);
    try {
      controller.logout();
      setLoading(false);
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
    }
  }

  /**
   * Refresh/restore session
   */
  async function refresh(): Promise<boolean> {
    if (!isBrowser()) {
      return false;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await controller.restoreSession();
      setLoading(false);
      return result;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return false;
    }
  }

  /**
   * Get the API client
   */
  function getClient(): GreyClient {
    return controller.getClient();
  }

  return {
    data,
    loading,
    error,
    login,
    logout,
    refresh,
    getClient,
  };
}

export type { AuthState, AuthConfig };
