// 14-TypeScript/Grey Multi-Tenant/packages/grey-react-native/src/hooks/useProjects.ts
/**
 * Grey React Native - useProjects Hook
 *
 * Provides projects state and actions for React Native components.
 * Wraps the ProjectsController from @grey/adapters.
 * Mobile-safe: no browser/DOM APIs.
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import {
  ProjectsController,
  type ProjectsState as CoreProjectsState,
  type CreateProjectInput,
  type GreyClient,
  type Project,
  type Pagination,
} from '@grey/adapters';

// ============================================================
// Types
// ============================================================

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * Projects data shape
 */
export interface ProjectsData {
  projects: Project[];
  pagination: Pagination | null;
}

/**
 * Projects hook return type
 */
export interface UseProjectsReturn {
  data: ProjectsData;
  loading: boolean;
  error: GreyError | null;
  listProjects: (page?: number, pageSize?: number) => Promise<void>;
  createProject: (input: CreateProjectInput) => Promise<Project | null>;
}

// ============================================================
// Error Normalization
// ============================================================

/**
 * Normalize any error into the standard error shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return {
      message: err.message,
      raw: err,
    };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return {
    message: 'An unknown error occurred',
    raw: err,
  };
}

// ============================================================
// Hook Implementation
// ============================================================

/**
 * useProjects Hook
 *
 * Provides projects state and actions.
 * Must be used within a GreyProvider or with a client.
 *
 * @param client - Optional GreyClient for standalone usage
 */
export function useProjects(client?: GreyClient): UseProjectsReturn {
  const controllerRef = useRef<ProjectsController | null>(null);
  const [data, setData] = useState<ProjectsData>({
    projects: [],
    pagination: null,
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<GreyError | null>(null);

  // Track if component is mounted
  const mountedRef = useRef(true);
  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // Initialize controller
  useEffect(() => {
    if (!client) return;

    const controller = new ProjectsController(client);
    controllerRef.current = controller;

    const unsubscribe = controller.subscribeToList((state: CoreProjectsState) => {
      if (mountedRef.current) {
        setData({
          projects: state.projects,
          pagination: state.pagination,
        });
        setLoading(state.isLoading);
        if (state.error) {
          setError({ message: state.error });
        }
      }
    });

    return () => {
      unsubscribe();
    };
  }, [client]);

  /**
   * List projects with pagination
   */
  const listProjects = useCallback(async (page = 1, pageSize = 20): Promise<void> => {
    const controller = controllerRef.current;
    if (!controller) {
      setError({ message: 'Projects controller not initialized' });
      return;
    }

    setLoading(true);
    setError(null);

    try {
      await controller.loadList(page, pageSize);
      if (mountedRef.current) {
        setLoading(false);
      }
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
    }
  }, []);

  /**
   * Create a new project
   */
  const createProject = useCallback(async (input: CreateProjectInput): Promise<Project | null> => {
    const controller = controllerRef.current;
    if (!controller) {
      setError({ message: 'Projects controller not initialized' });
      return null;
    }

    setLoading(true);
    setError(null);

    try {
      const project = await controller.createProject(input);
      if (mountedRef.current) {
        setLoading(false);
      }
      return project;
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
      return null;
    }
  }, []);

  return {
    data,
    loading,
    error,
    listProjects,
    createProject,
  };
}

// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/hooks/useProjects.ts
/**
 * Grey Solid - useProjects Hook
 *
 * Solid hook for projects state and actions.
 * Wraps ProjectsController from @grey/adapters.
 * Exposes: data, loading, error, listProjects, createProject.
 */

import { createSignal, onMount, onCleanup, type Accessor } from 'solid-js';
import {
  ProjectsController,
  type ProjectsState,
  type CreateProjectInput,
} from '@grey/adapters';
import type { GreyClient, Project, Pagination } from '@grey/core-client';

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * Projects data structure
 */
export interface ProjectsData {
  projects: Project[];
  pagination: Pagination | null;
}

/**
 * useProjects hook return type
 */
export interface UseProjectsReturn {
  /** Projects data (list and pagination) */
  data: Accessor<ProjectsData>;
  /** Loading state */
  loading: Accessor<boolean>;
  /** Error state */
  error: Accessor<GreyError | null>;
  /** List projects with optional pagination */
  listProjects: (page?: number, pageSize?: number) => Promise<void>;
  /** Create a new project */
  createProject: (input: CreateProjectInput) => Promise<Project | null>;
}

/**
 * Normalize error into standard shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return { message: err.message, raw: err };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return { message: 'An unknown error occurred', raw: err };
}

/**
 * useProjects hook
 *
 * @param client - Grey API client
 * @returns Projects hook with data, loading, error, and actions
 */
export function useProjects(client: GreyClient): UseProjectsReturn {
  const controller = new ProjectsController(client);

  // Create signals
  const [data, setData] = createSignal<ProjectsData>({
    projects: [],
    pagination: null,
  });
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<GreyError | null>(null);

  // Subscribe to controller state changes
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    unsubscribe = controller.subscribeToList((state: ProjectsState) => {
      setData({
        projects: state.projects,
        pagination: state.pagination,
      });
      setLoading(state.isLoading);
      if (state.error) {
        setError({ message: state.error });
      }
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  /**
   * List projects with optional pagination
   */
  async function listProjects(page = 1, pageSize = 20): Promise<void> {
    setLoading(true);
    setError(null);
    try {
      await controller.loadList(page, pageSize);
      setLoading(false);
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
    }
  }

  /**
   * Create a new project
   */
  async function createProject(input: CreateProjectInput): Promise<Project | null> {
    setLoading(true);
    setError(null);
    try {
      const project = await controller.createProject(input);
      setLoading(false);
      return project;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return null;
    }
  }

  return {
    data,
    loading,
    error,
    listProjects,
    createProject,
  };
}

export type { ProjectsState, CreateProjectInput };
