// 14-TypeScript/Grey Multi-Tenant/packages/grey-react-native/src/hooks/useQuery.ts
/**
 * Grey React Native - useQuery Hook
 *
 * Generic data fetching hook with loading and error states.
 * Wraps the QueryController from @grey/adapters.
 * Mobile-safe: no browser/DOM APIs.
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import {
  QueryController,
  type QueryState as CoreQueryState,
  type QueryOptions as CoreQueryOptions,
} from '@grey/adapters';

// ============================================================
// Types
// ============================================================

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * Query hook options
 */
export interface UseQueryOptions<T> {
  queryFn: () => Promise<T>;
  enabled?: boolean;
  onSuccess?: (data: T) => void;
  onError?: (error: Error) => void;
}

/**
 * Query hook return type
 */
export interface UseQueryReturn<T> {
  data: T | null;
  loading: boolean;
  error: GreyError | null;
  executeQuery: () => Promise<T | null>;
}

// ============================================================
// Error Normalization
// ============================================================

/**
 * Normalize any error into the standard error shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return {
      message: err.message,
      raw: err,
    };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return {
    message: 'An unknown error occurred',
    raw: err,
  };
}

// ============================================================
// Hook Implementation
// ============================================================

/**
 * useQuery Hook
 *
 * Fetch data with loading states and error handling.
 *
 * @param options - Query options including queryFn
 */
export function useQuery<T>(options: UseQueryOptions<T>): UseQueryReturn<T> {
  const { queryFn, enabled = true, onSuccess, onError } = options;

  const controllerRef = useRef<QueryController<T> | null>(null);
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(enabled);
  const [error, setError] = useState<GreyError | null>(null);

  // Track if component is mounted
  const mountedRef = useRef(true);
  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  // Initialize controller
  useEffect(() => {
    const coreOptions: CoreQueryOptions<T> = {
      queryFn,
      enabled,
      onSuccess,
      onError,
    };

    const controller = new QueryController(coreOptions);
    controllerRef.current = controller;

    const unsubscribe = controller.subscribe((state: CoreQueryState<T>) => {
      if (mountedRef.current) {
        setData(state.data);
        setLoading(state.isLoading);
        if (state.error) {
          setError(normalizeError(state.error));
        } else {
          setError(null);
        }
      }
    });

    // Execute initial query if enabled
    if (enabled) {
      controller.execute();
    }

    return () => {
      unsubscribe();
    };
  }, [enabled]);

  /**
   * Execute the query manually
   */
  const executeQuery = useCallback(async (): Promise<T | null> => {
    const controller = controllerRef.current;
    if (!controller) {
      // Create a new controller for manual execution
      const newController = new QueryController({
        queryFn,
        enabled: true,
        onSuccess,
        onError,
      });
      controllerRef.current = newController;
    }

    setLoading(true);
    setError(null);

    try {
      const result = await controllerRef.current!.execute();
      if (mountedRef.current) {
        setLoading(false);
      }
      return result;
    } catch (err) {
      if (mountedRef.current) {
        setError(normalizeError(err));
        setLoading(false);
      }
      return null;
    }
  }, [queryFn, onSuccess, onError]);

  return {
    data,
    loading,
    error,
    executeQuery,
  };
}

// 14-TypeScript/Grey Multi-Tenant/packages/grey-solid/src/hooks/useQuery.ts
/**
 * Grey Solid - useQuery Hook
 *
 * Solid hook for generic data fetching.
 * Wraps QueryController from @grey/adapters.
 * Exposes: data, loading, error, executeQuery.
 */

import { createSignal, onMount, onCleanup, type Accessor } from 'solid-js';
import { QueryController, type QueryOptions, type QueryState } from '@grey/adapters';

/**
 * Normalized error shape
 */
export interface GreyError {
  message: string;
  code?: string;
  status?: number;
  raw?: unknown;
}

/**
 * Query hook options
 */
export interface UseQueryOptions<T> {
  /** Async function that fetches data */
  queryFn: () => Promise<T>;
  /** Whether to execute on creation (default: false) */
  enabled?: boolean;
  /** Called on success */
  onSuccess?: (data: T) => void;
  /** Called on error */
  onError?: (error: Error) => void;
}

/**
 * useQuery hook return type
 */
export interface UseQueryReturn<T> {
  /** Query result data */
  data: Accessor<T | null>;
  /** Loading state */
  loading: Accessor<boolean>;
  /** Error state */
  error: Accessor<GreyError | null>;
  /** Execute the query */
  executeQuery: () => Promise<T | null>;
}

/**
 * Normalize error into standard shape
 */
function normalizeError(err: unknown): GreyError {
  if (err instanceof Error) {
    return { message: err.message, raw: err };
  }
  if (typeof err === 'string') {
    return { message: err };
  }
  return { message: 'An unknown error occurred', raw: err };
}

/**
 * useQuery hook
 *
 * @param options - Query options
 * @returns Query hook with data, loading, error, and executeQuery action
 */
export function useQuery<T>(options: UseQueryOptions<T>): UseQueryReturn<T> {
  const controller = new QueryController<T>({
    queryFn: options.queryFn,
    enabled: options.enabled,
    onSuccess: options.onSuccess,
    onError: options.onError,
  });

  // Create signals
  const [data, setData] = createSignal<T | null>(null);
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<GreyError | null>(null);

  // Subscribe to controller state changes
  let unsubscribe: (() => void) | undefined;

  onMount(() => {
    unsubscribe = controller.subscribe((state: QueryState<T>) => {
      setData(() => state.data);
      setLoading(state.isLoading);
      if (state.error) {
        setError(normalizeError(state.error));
      } else {
        setError(null);
      }
    });
  });

  onCleanup(() => {
    unsubscribe?.();
  });

  /**
   * Execute the query
   */
  async function executeQuery(): Promise<T | null> {
    setLoading(true);
    setError(null);
    try {
      const result = await controller.execute();
      setLoading(false);
      return result;
    } catch (err) {
      setError(normalizeError(err));
      setLoading(false);
      return null;
    }
  }

  return {
    data,
    loading,
    error,
    executeQuery,
  };
}

export type { QueryOptions, QueryState };
